export const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    slug: "wireless-headphones",
    price: 450000,
    stock: 12,
    category: 1,
    category_name: "Electronics",
    rating: 4,
    img: "https://picsum.photos/seed/headphones/300/200",
  },
  {
    id: 2,
    name: "Smartphone",
    slug: "smartphone",
    price: 700000,
    stock: 5,
    category: 1,
    category_name: "Electronics",
    rating: 4.5,
    img: "https://picsum.photos/seed/smartphone/300/200",
  },
  {
    id: 3,
    name: "Laptop",
    slug: "laptop",
    price: 1500000,
    stock: 8,
    category: 1,
    category_name: "Electronics",
    rating: 4.7,
    img: "https://picsum.photos/seed/laptop/300/200",
  },
  {
    id: 4,
    name: "Fiction Novel",
    slug: "fiction-novel",
    price: 120000,
    stock: 20,
    category: 2,
    category_name: "Books",
    rating: 4.2,
    img: "https://picsum.photos/seed/novel/300/200",
  },
  {
    id: 5,
    name: "Science Textbook",     
    slug: "science-textbook",
    price: 80000,
    stock: 15,
    category: 2,
    category_name: "Books",
    rating: 4.5,
    img: "https://picsum.photos/seed/textbook/300/200",
  },
];